# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Welcome on board!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script

  test:  
    steps:
    
    - name: Test fields
      run: echo Checking Rocket setup properties...
      run: sh test-fields.sh
      
    - name: Test format
      run: echo Checking values format...
      run: sh test-format.sh
      
    - name: Test consistency
      run: echo Checking data consistency...
      run: sh test-consistency.sh
  
  deploy:
    steps:
    - name: Deployment
      run: echo "Rocket has been launched!.
