# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Welcome on board!"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

        # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Welcome on board!"

      - run: echo "Checking Rocket setup properties..."
      - name: Test fields
        run: sh test-fields.sh
        
      - run: echo "Checking values format..." 
      - name: Test format
        run: sh test-format.sh
        
      - run: echo "Checking data consistency..."
      - name: Test consistency
        run: sh test-consistency.sh
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Deployment
      run: echo "Rocket has been launched!".
