name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run a one-line script
        run: echo Welcome on board!
      - name: Run a multi-line script

  test:  
    steps:    
    - name: Test fields
      run: echo Checking Rocket setup properties...
      run: sh test-fields.sh
      
    - name: Test format
      run: echo Checking values format...
      run: sh test-format.sh
      
    - name: Test consistency
      run: echo Checking data consistency...
      run: sh test-consistency.sh
  
  deploy:
    steps:
    - name: Deployment
      run: echo "Rocket has been launched !
